### PR TITLE
Profile analysis for Boston and Cambridge

### PR DESCRIPTION
**Pull request by shreyapandit**
This PR is a work in progress and will be mainly useful for providing a nice UI to look through the notebooks which pertain to the profile analysis.

### CODE REVIEW

**Comment by shreyapandit** [comment]
Looks like pylint has failed...will look into it

**Comment by j-t-t** [comment]
Certainly notebooks aren't included in the codecov metrics at this point. If @shreyapandit is writing a pkl file as part of the train_model, I might throw in a test for that but it would be simple/quick to do

**Comment by bpben** [comment]
Just took a look at the pickle, it looks like it's the same as the
seg_w_predicted.csv that comes out of the model.  Is that right, Shreya?

**Comment by terryf82** [comment]
If we're aligned on focusing development on segment-level predictions in the future I think it would be good to update this notebook to reflect that. This still references a lot of week-level properties and I found it a little difficult to follow through for a city (Brisbane) that had segment-level preds.

**Comment by shreyapandit** [comment]
Closing this for the moment, will reopen once we agree on a standard method to use for all cities.

**Pull request closed without merging**
