### PR TITLE
Showcase

### PR DESCRIPTION
**Pull request by terryf82**
Evaluating ability to merge showcase code into master and have a unified viz branch.

### CODE REVIEW

**Comment by terryf82** [comment]
@alicefeng this should now be ready for merging, can you just double check that everything looks fine from a viz perspective?

I've had to make some small changes to the loading of data for 'standalone' viz mode. The city selector will appear even if there is only one city being run, but then the same code works for showcase / multi-city mode.

The path to config.js is the local directory, but I swap this out in the showcase Dockerfile to point to the S3-hosted version.

**Comment by terryf82** [comment]
You should be able to swap to the showcase branch and run it locally, once
you generate or modify the config.js file according to the new spec.

**Comment by terryf82** [comment]
@alicefeng Can you try this again and see if your local viz loads without error?

**Comment by shreyapandit** [comment]
screen shot 2019-02-26 at 10 34 05 am

I am unable to choose city and the map doesnt load. I compiled and ran the branch through docker:

```
- docker build --tag datafordemocracy/crash-model:showcase .
- docker run -d -p 8080:8080 --name bcm.local -v `pwd`:/app datafordemocracy/crash-model:showcase
```

where pwd appends my local path repo

**Comment by shreyapandit** [comment]
screen shot 2019-02-26 at 9 34 54 pm

**Pull request merged**
