### PR TITLE
Aesthetic improvements to viz

### PR DESCRIPTION
**Pull request by alicefeng**
Finally merging in long-awaited improvements to the crash layer in the viz:
- change crash circles back to purple
- make crash circles larger
- add in dates of crashes to crash popups
- generate new file `crashes_rollup.geojson` in pipeline to enable crash dates to be displayed

### CODE REVIEW

**Comment by j-t-t** [comment]
Can you talk in a little more detail about what you're trying to do in standardize_crashes? It sort of looked like the main goal was to output your new crash rollup file. Is there a purpose to taking out those blocks of code

It looks like you took datadir and city out as arguments to read_standardized_fields because they weren't used in that function. You'll need to update all calls to read_standardized_fields in src/data_standardization/tests/test_standardize_crashes.py to also remove those arguments.

With regard to your changes to writing the file, I'd move all of what you're adding into its own function, instead of part of it in main and part of it in its own function. It will be easier to write a test that way. Also, please add a description at the top of your new function inside of triple quotes, that says what it does and also gives information about what the arguments are to the function.

**Comment by alicefeng** [comment]
I'm not sure what happened with the deleted chunks of code.  I did not remove anything from the script, only added to it so something weird happened there.  At any rate, I think I've restored all of the deleted lines.  I've also moved all of the code for rolling up the crashes into a function except for the part where the geojson file actually gets written.

Let me know if there are any other edits needed.

**Comment by alicefeng** [comment]
Added a test for `make_crash_rollup`.  I used `assert_frame_equal` from [pandas' testing module](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.testing.assert_frame_equal.html) to test if the two dataframes were the same.  Let me know if it'll cause any problems to use that (it looks like my test passed).

**Comment by j-t-t** [comment]
Looks great!

**Comment by terryf82** [comment]
@alicefeng is this ready for deployment to the showcase? If so, do we want to try and get https://github.com/Data4Democracy/crash-model/pull/218 merged in at the same time?

**Comment by alicefeng** [comment]
@terryf82 Yes, this can be pushed to the showcase! I agree about merging #218 in along with it.

**Pull request merged**
