### PR TITLE
Data standards

### PR DESCRIPTION
**Pull request by terryf82**
set default city lat/lng in new config from geocoded response

### CODE REVIEW

**Comment by j-t-t** [comment]
Let's get Shreya's initialize_city test changes into master before we merge this so we can decide whether you should flesh out the test you wrote or just update her test

**Comment by j-t-t** [comment]
The test_brisbane_config file is getting written to src/. Can you create a temp directory and write there instead?

**Comment by terryf82** [comment]
@j-t-t thanks, path updated and CI tests running now.

**Comment by j-t-t** [comment]
Sorry, I should have been more specific. Best to use a tmpdir created for this test. Test functions can take an argument called tmpdir and you can use that. https://docs.pytest.org/en/latest/tmpdir.html

**Comment by terryf82** [comment]
@j-t-t thanks, updated with proper use of tmpdir fixture.

**Pull request merged**
